run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/towe75/nri-plugin-systemd
